In [1]:
import torch
import torch.nn as nn




In [9]:
t = torch


tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [5]:
class DQNNetwork(nn.Module):
    def __init__(self, input_shape,fc1_dim, fc2_dim, number_actions, batch_size) -> None:
        super(DQNNetwork,self).__init__()
        self.batch_size= batch_size

        self.net = nn.Sequential(
            
                nn.Linear(input_shape,fc1_dim),
                nn.ReLU(),
                nn.Linear(fc1_dim,fc2_dim),
                nn.ReLU(), 
                nn.Linear(fc2_dim, number_actions)
            
        )
    def forward(self,observations):
        # observations dimension --> tensor(batch_size,3,32,32)
        observations = observations.view(self.batch_size,-1) # 3*32*32
        #dimesion (5,3*32*32)
        return self.net(observations)

In [6]:
model = DQNNetwork(input_shape=256,fc1_dim=256,fc2_dim=256,number_actions=4,batch_size=5)
test_input = torch.rand(5,16,16)


model(test_input)

tensor([[ 0.1470,  0.0091, -0.0193, -0.0246],
        [ 0.0936, -0.0073,  0.0246, -0.0025],
        [ 0.1534,  0.0610,  0.0177,  0.0177],
        [ 0.1101,  0.0706,  0.0068, -0.0046],
        [ 0.1618,  0.0610,  0.0208,  0.0034]], grad_fn=<AddmmBackward>)

In [7]:
criterion = nn.CrossEntropyLoss()

In [11]:
inputs = torch.tensor([32,40,100])
targets= torch.tensor([0])

In [1]:
import numpy as np
import torch


In [3]:
k = np.zeros((4,4))

In [15]:
def unpack(t):
    return np.zeros((*t.shape,4))

In [20]:
np.zeros((3,3),dtype=np.bool8)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])